[package]
name = "hello"
version = "0.1.0"
authors = ["IDA Kenichiro <ida.kenichiro@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
clap-verbosity-flag = "^0.3.0"
env_logger = "^0.7.1"
log = "^0.4.0"
structopt = "^0.3.5"
